### ISSUE TITLE
[Navigation mode] Useless handles?

### ISSUE THREAD

**Issue by Olf0** [rinigus/pure-maps#253]
When Pure Maps is in navigation mode, at the border of the map view to the top section, a "pull handle" (I lack a better term for it) is displayed:
* It is really hard to "grab" (tested on a Jolla 1 and an Xperia X)
* Its "focus point" for grabbing it seems to be a bit above it, while I would expect the "focus point" for grabbing the "pull handle" to be right on it (due to its non-border position on the screen).
* There seems to be flaw in the usage logic: When I manage to grab it and pull it fully up, the "pull handle" vanishes.  I would have expected it to be displayed in the centre of the upper screen border (with a "focus point" for grabbing slightly below it).  I have not found a way to let all the status information being displayed again without leaving the main window in navigation mode (entering the navigation settings and hitting Pause&Start or Reroute works).

Personally I don't like that "pull handle" in the "middle" of the screen (i.e., prominently visible in its default position), hence my mutually exclusive suggestions are (preferring the first):
* Eliminating the "pull handling" and considering other means to toggle the visibility of the status information when the main window is in navigation mode.  E.g. by a double-tap on the status information area, while a double tap on the map displayed would still work as usual.  Or a logpress on the status area.  Or some swipe.
Using this toggle action once would hide the status information areas, using it a second time would display them again.
* Displaying the "pull handle" in the centre of the upper screen border when the status area is invisible, to be able to pull it back in (i.e., making it visible again).

IMHO this is just a minor usability / look&feel issue.

To illustrate what this issue is about:
![puremaps-navigation-handle png](https://user-images.githubusercontent.com/16547876/57813445-68372e00-7770-11e9-9876-34634efda5a8.png)

**Comment by Olf0** [comment]
Oh, Pure Maps seems to exit navmode completely, when the "pull handle" is pulled fully up.

I also posted the wrong screenshot, I was primarily addressing the "pull handle" depicted below.  This one is additionally looking off-centre due to the screen layout.
The behaviour is the same for both "pull handles": Exit navigation mode 

As this can be easily and better understandably accomplished by tapping on the status information area and hitting "Clear" then, my better informed suggestion is now:
Please eliminate the two "pull handles", because the are superfluous, visually distracting, hard to use, hard to understand their function etc.

Originally intended screenshot for the original issue description:
![puremaps-handle2 png](https://user-images.githubusercontent.com/16547876/57814547-40e26000-7774-11e9-8eec-d2b63d6fa60c.png)

**Comment by rinigus** [comment]
It was introduced to allow quickly to dismiss the route. In this respect, it acts exactly as a dismissable panel with search results and uses the same visual clue. The difference is in reach (top instead of bottom), motion direction (out from body), and, for landscape, really hard to grab. 

Let's keep this issue open and see if others will be asking for the same. Its surely not ideal and maybe should be just dropped for navigation, as you suggest.

**Comment by Olf0** [comment]
Thanks for pointing out the two handles I missed.
* Handle #3: ![Screenshot_20190517_001](https://user-images.githubusercontent.com/16547876/57957824-01477f80-78fe-11e9-95c7-ffe3b7662df9.png)
* And by tapping on the map once then, handle #4 is presented: ![Screenshot_20190517_002](https://user-images.githubusercontent.com/16547876/57957847-13c1b900-78fe-11e9-8783-fbc8f88a1173.png)


Although slightly different (search instead of navigation), the situation for the user is basically the same:
* A tap on the address in the bottom field of the search status information nicely opens the search window again, both in screenshot #3 and #4.
* For consistent behaviour when tapping on the status information area in navigation mode, it would be nice if a tap on the top field (detailed location information) of the search status area in screenshot #3 sends one back to the search window, too (currently a tap on it triggers nothing).

I see, that I was "jumping at conclusions", without really understanding the usability concept of this part of the GUI:
* If one does not eagerly try to "grab the handle" but starts sliding up or down anywhere in an information area, the panel(s) slide out easily.  Hence  the "hard to grab handle"- usability issue is non-existent.
* Thus these handles primarily indicate a slideable panel.  I didn't understand this aspect before.  Hence the handles ought to stay, IMO.

P.S.: And I discovered handle #5, which also behaves the same, i.e. correctly (now that I have understood how to use them).
![Screenshot_20190517_006](https://user-images.githubusercontent.com/16547876/57957921-51bedd00-78fe-11e9-977e-3abf09bf8bd0.png)

**Comment by Olf0** [comment]
Even more informed conclusions (preliminary, as usual ;) ):
* Thank you for taking your time to patiently discuss GUI usability.  A lengthy exchange before reaching some mutual understanding is often necessary to grasp the core of a GUI concept or perceived GUI workflow issue.
* So basically (hope to have fully understood this now) pulling one of the five handles exits the current navigation or search mode and returns to the plain map view.
But AFAICS, this is not fully consistent: When both panels with handles #1 and #5 are displayed, Pure Maps  stays in navigation mode after closing panel #5.
* I also gained a clearer understanding of why I perceive this behaviour as surprising:
  IMO a slideable panel (with handle) indicates a reversible action, here being able to slide the panel in and out in order to get a broader view of the map, but also being able to return to the former state (with the panel displayed), i.e. without leaving navigation or search mode.
  That is, why my second (originally: alternative) suggestion in the original issue report was to make the handles visible at the upper/ lower screen border after a panel has been swiped away.
* Exiting a current navigation or search should be an explicit user action, e.g. by tapping on an **X**.  This is directly available in the left of the lower field when in search or navigation mode, plus indirectly by tapping on a different area of the status information, which takes one back to the navigation or search window, where "**X** Clear" exits the current navigation or search.
  Hence the current behaviour of closing a panel irreversibly when swiped away just provides another way of exiting to the plain map view.  And it is implicit behaviour, which was surprising (at least me) and initially hard to comprehend (as my intention was to see more of the map but not exiting the current search or navigation).

But these are just usability and user workflow considerations, I have no idea how hard it is (and hence, if worth the effort) to implement:
* Still move the corresponding panel out, when it is swiped (or grabbed by its handle), but do not exit the current search or navigation.
* Display a handle at the screen border to pull the corresponding panel back in, restoring the original state.
* Unrelated to the two before: Consider jumping back to the search window, when tapping on the top field of panel #3 (containing the detailed location information). 

P.S.: As one can easily make Pure Maps display a screen as captured below (by searching while in navigation mode, and that even makes sense, i.e. "I wouldn't want it any other way"), I believe a "sliding back and forth" really would be much better than "exiting to plain map view".  Note that, depending on the size of the current search hit / lower panel, the two panels are overlapping as depicted or leave a small horizontal strip of the map still being displayed.
![Screenshot_20190517_007](https://user-images.githubusercontent.com/16547876/57957968-85016c00-78fe-11e9-94ff-e713fada7d88.png)

**Comment by rinigus** [comment]
Hi @Olf0,

sorry for late reply - was busy with many other things. But I hope its OK and we can continue the discussion.

In general, these handles indicate that the corresponding panel can be swiped away. For the swipe action to work, you can grab anywhere on the panel and move it away. For panel on the bottom, you move it out towards buttom. For top panel, its opposite. In this aspect, handles are good way of showing such swiping action and, as far as I understood, at least some users discovered via them that the panels are swipable. Similar notation is used on Android and iOS, as far as I have seen; not just SFOS.

The panel on the bottom can be used either to show current POI, current mode (search, nearby, navigation), or a mix of those with the current POI on the top and mode on bottom of the panel. The POI part is shown non-clickable, with the exception of the buttons (i, star, ...) that would bring you to the corresponding action with POIs. In this respect, its different from the current mode (such as search). The mode section, would bring you to the corresponding window (search, navigation settings, nearby). You could also dismiss such mode via X or swiping panel out. 

Since we are on gesture-based OS and gestures are getting into other platforms as well, I prefer to keep X and swipe action as well. In practice, I use swipe usually to get out of the mode.

I guess, the main issue was that the swiping action is irreversible. Its hard for me to compare right now and see if it is normal to have it reversible or not. As for adding X to navigation bar - would have to keep that in mind when I get to look through that bar design. 

As for reversible handle swipe off/on - bottom of the application is reserved for list of applications by SFOS. Hence, we cannot use that gesture, even if we would like to.

I hope I replied to you. Let me know if I am missing something.

**Comment by Olf0** [comment]
All fine and wel understandable (e.g. I usually reply with much more delay). ☺️

**Comment by Olf0** [comment]
An attempt to gather more opinions on this: https://talk.maemo.org/showthread.php?p=1557479#post1557479

**Comment by rinigus** [comment]
The handles have been removed in navigation mode with more explicit button(s) added, depending on the state. For POI data, search, route calculation modes the handles stayed to show that it can be swiped out. Closing it here, please open a new one against the next release if it is inconsistent or still disturbing.

**Comment by Olf0** [comment]
Thanks!
I will try to take a look at it in the next weeks.

**Comment by rinigus** [comment]
not released yet :)

**Comment by Olf0** [comment]
... but definitely looking good now!
Thank you.
