### ISSUE TITLE
Pasting into address field does not work

### ISSUE THREAD

**Issue by jonnius** [rinigus/pure-maps#370]
Pasting into address field does not work in ubports version.

**Comment by rinigus** [comment]
Does it work in the other fields? Is there some special call in QML to enable pasting in UT?

**Comment by jonnius** [comment]
There is no context menu (tapping and holding) on any text field, unless the API fields. I think you once fixed them? I don't have experience with QML tbh.

**Comment by rinigus** [comment]
I think its due to the use of SearchFieldPL in Ubuntu. Namely, its using QtControls version. For UBports, we need to make a new one that relies on UC.TextField (or something for search fields). In the code, we use `text` property and `search` signal. 

@StefWe , do you want to look into it and make UBports version for SearchFieldPL as well?

**Comment by StefWe** [comment]
Unfortunately I don't have any free time right now. If it is June/July and not solved, I will have a look at it.

**Comment by rinigus** [comment]
Thanks, we will ping you then if it's not solved by that time

**Comment by rinigus** [comment]
@StefWe Ping. We are in June and approaching July

**Comment by StefWe** [comment]
Some things do not solve themselves :-)

I will have a look on that.

**Comment by rinigus** [comment]
Assuming that is fixed now with @StefWe PR. Thank you!
