### ISSUE TITLE
[ubports] Unable to add map provider in Ubuntu touch

### ISSUE THREAD

**Issue by dano6** [rinigus/pure-maps#376]
According to [maps/README.md](https://github.com/rinigus/pure-maps/blob/master/maps/README.md) i added  to `~/.local/share/pure-maps.jonnius/maps` json file with custom map provider.
Pure-maps UI is now broken (see image below) and `dmesg` shows some Apparmor denials  [log here](https://pastebin.com/gRtQuUhT)

I am using Nexus 5 with OTA-12-rc, I can provide .json file if necessary (worked on PC before).

![dk](https://user-images.githubusercontent.com/16964594/77230660-b0439000-6b8d-11ea-9de4-d586c8abcab2.png)

**Comment by rinigus** [comment]
I don't see any major issues that could be caused by it in the log. As for whether the style can be loaded in UBPorts, I don't know whether its allowed by permissions. Sounds like it is.

Try to remove the style. After that start Pure Maps and try to change map provider. This should reload the style. It seems like the error has happened, possibly due to the faulty style, and messed up the cache. I would expect that switching to HERE and back to Mapbox should fix the buttons.

**Comment by rinigus** [comment]
PS: Let me know how it went

**Comment by dano6** [comment]
I had just stupid syntax error in my json, I slept for 2 hours and it helped :smile: After I pushed style from PC to phone I deleted 1 line and doesn't deleted comma in line before. It is working nicely now, thanks for the answer.

**Comment by rinigus** [comment]
Excellent! If it useful generally, consider submitting your style as PR.
