### ISSUE TITLE
Builds for new branch

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#423]
Test builds for

- [x] UBPorts
- [x] Flatpak
- [x] Fedora

**Comment by rinigus** [comment]
UBPorts:

As the build is using `qmake` now, clickable probably has to be converted to something similar to OSM Scout Server. Few notes

- injecting keys happens now during `make install` automatically. No need to do it before

- specify flavor using FLAVOR=ubports on `qmake` step

- DEFAULT_FALLBACK_STYLE is set to `suru` already automatically

- qmlrunner is not needed anymore

Not sure what to do with:

- for some reason we have specified FULLNAME (pure-maps.jonnius) which was somehow used in parallel with NAME (pure-maps). Maybe something to do with how you call it from scripts?

- we were setting `"${XDG_CACHE_HOME:-$HOME/.cache}"/FULL_NAME/tmp` as `TMPDIR`. Don't remember why

cc/ @jonnius

**Comment by jonnius** [comment]
About the two "not sure"s:
* The [commit](https://github.com/rinigus/pure-maps/commit/d539c9801fb93fed3685c6400e7b8a13707c9af5) that adds `FULLNAME` explains it. The `FULLNAME` (`pure-maps.jonnius`) is different from `NAME` (`pure-maps`). Standard paths must be crafted from `FULLNAME`. Otherwise app confinement will not allow us to access them.
* Iirc, app confinement did prevent us from using whatever Pure Maps uses as `TMPDIR` by default.

**Comment by rinigus** [comment]
FULLNAME: Should we then rename app into `pure-maps.jonnius` or you can somehow execute it from terminal as `pure-maps` right now? Asking as we don't seem to have any issue with OSM Scout Server and I can't figure out why we have such difference...

OK, TMPDIR is probably set as `/tmp` on device or similar as a default. Maybe we should set it in `.desktop` file used by UBPorts. As in https://unix.stackexchange.com/questions/459172/set-multiple-environment-variables-in-desktop-file

**Comment by jonnius** [comment]
FULLNAME: I'll try. Let's see if it has any side effects on Qt and AppArmor.

TMPDIR: Sure, we can do that. Whatever you think is the best suitable solution.
