### ISSUE TITLE
Voice navigation volume issues in combination with playing music

### ISSUE THREAD

**Issue by poVoq** [rinigus/pure-maps#430]
On PureMaps 2.0.0 on Ubuntu Touch I can't use the voice navigation in combination with playing music, as the volume of the voice is way to low. I am using it over Bluetooth in my car.

It does somehow lower the audio volume for the music when playing voice directions, but the voice sound volume seems to also get reduced resulting in lower volume music and almost in-audible voice navigation messages.

It works fine when using voice navigation exclusively, so I guess the specific lowering of other audio volume must be at fault.

**Comment by rinigus** [comment]
Did it start recently, with 2.0.0 update? Could relate to some issue with UT sound...

**Comment by poVoq** [comment]
No, I think this also happend pre-2.0 but I only switched using UT as a daily driver recently and thus used Puremaps more. But I am 75% sure I noticed that behavior in tests before.

**Comment by jonnius** [comment]
Could you please install [uVolMan](https://open-store.io/app/uvolman.mateosalta) and make sure that the `sink-input-by-media-role:alter` has a high volume? This seems to be the setting that applies to sound output since 2.0. We had a change there to make it pause Music for sound output and then return to the music afterwards, which works perfectly well for me.

**Comment by poVoq** [comment]
That worked, thanks. Strange that a "alert" sound is by default the lowest relative volume of only around 50%.
