### ISSUE TITLE
Make it possible to set default profile

### ISSUE THREAD

**Issue by PureTryOut** [rinigus/pure-maps#517]
Right now you can change individual default components like BASEMAP or GEOCODER in packaging, but it would be nice to be able to set the entire profile rather than the individual components. In my case I would like to have the default profile be "offline" and to do that I now have to change everything individually.

**Comment by rinigus** [comment]
Default profile is set separately and not through changes in default basemap/geocoder and such. I will add separate defaults for different profiles and we would have to set default profile similar way to those. As such, there is more work on it to be done.

**Comment by rinigus** [comment]
Fixed in cmake branch.

Default profile is set using -DDEFAULT_PROFILE option. Selection is either online or offline. Option name was selected for consistency with other DEFAULT_* options. Note that the basemap, geocoder and others are for online and mixed profiles only.

Closing over here, soon should be possible to merge cmake to master.
