### ISSUE TITLE
Even with the offline profile enabled Pure-Maps still complains about missing Mapbox API key on startup

### ISSUE THREAD

**Issue by PureTryOut** [rinigus/pure-maps#522]
Which doesn't make sense, the offline profile provides everything Pure-Maps might need.

**Comment by PureTryOut** [comment]
Actually, this seems to have been fixed since the last version. I can't reproduce it on the latest master :+1:

**Comment by PureTryOut** [comment]
Uhm, nope. I can reproduce it with 2.7.1 still, which is definitely newer than master back then.

Re-opening.

**Comment by rinigus** [comment]
Fixed via 4ecdddae3ee335248f6b235e5dd0a0941ea78c15

With the next release, you will be able to specify `cmake -DDEFAULT_FONTPROVIDER=osmscout ...` to use OSM Scout Server instead of Mapbox for fonts. The corresponding error box will not be shown. This font provider is important for raster tile  basemap servers (OpenCycleMap for example) as it is used for showing overlayed symbols on map (POIs and search results)

Closing, please reopen if still not working.
