### ISSUE TITLE
Donation option

### ISSUE THREAD

**Issue by Camiropan** [rinigus/pure-maps#668]
Hi, i would like to donate to this application. Unfortunately i couldn't find a way to do so.
Am i missing something or is there no "official" way to donate yet?

**Comment by jonnius** [comment]
You can donate to rinigus via [his donation page](https://rinigus.github.io/donate/).

**Comment by rinigus** [comment]
Sorry for late reply - was away. Indeed, donation links are available at some places. There is no donation option for Pure Maps as to some organization behind it as there is no such organization. For making some ORG, we would need a bunch of active code contributors, something that haven't happened during these years. Iff we get to that stage then we can consider making Pure Maps ORG and its specific donation link.

Closing this issue here,
