### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#82]
From OpenRepos: 

So the question is: is it possible to start pure maps by external command with coordinates or address search?

**Comment by zeonin** [comment]
I'd definitely be looking for something like this!

It would be great if pure maps could also support opening a `geo:` URI so that it could be launched by xdg-open (either in addition to or in lieu of command line flags).

**Comment by rinigus** [comment]
I started looking into it.

**Comment by rinigus** [comment]
While command line arguments are available through QML at `Qt.application.arguments`, its not clear how to forward / communicate if Pure Maps was started already and then called again (while running) with some command line arguments. 

Would require some research, would look into it later unless solution presents itself.

**Comment by zeonin** [comment]
I suspect (though I'm totally new to Sailfish development so I could be totally wrong) that that could be accomplished by using DBus.

It looks like that's how the Jolla Notes app does it for example: using the "new note" button sends a DBus request to the application. If it's up and running it services the request, otherwise a new instance is started which then does so.

**Comment by xXSparkeyy** [comment]
Adding the following to RootPage.qml (other files might be more suitable) did the trick for me.

```
 DBusAdaptor { 
        id: dbus
        bus: DBus.SessionBus
        service: 'org.ringius.pureMaps'
        iface: 'org.ringius.pureMaps'
        path: '/org/ringius/dbus'
        xml: ' <interface name="org.ringius.pureMaps">\n'
        + ' <method name="showPOI" >\n'
        + '<arg name="lat" type="s" direction="in" />\n'
        + '<arg name="lon" type="s" direction="in" />\n'
        + '</method>\n'
        + ' </interface>\n'
        function showPOI( lat, lon ) { _showPOI( lon, lat ) }
      } 
```
... and added _showPOI as function.

Showing the poi witth the following line

` dbus-send --print-reply --dest=org.ringius.pureMaps '/org/ringius/dbus' org.ringius.pureMaps.showPOI string:'12.34' string:'12.34' `

**Comment by rinigus** [comment]
Thank you! I still have to add few things in desktop file, flatpak exe scripts and probably add an exe script for Sailfish as well. So, not closed yet

**Comment by xXSparkeyy** [comment]
Nice for desktop files if you dont already have them you could try adding the following:
 
/usr/share/applications/[...].desktop
[Desktop Entry]
Type=Application
Name=pure-maps
NoDisplay=true
Icon=harbour-pure-maps
X-Maemo-Service=io.github.ringius.pureMaps
X-Maemo-Object-Path=/io/github/ringius/pureMaps
X-Maemo-Method=io.github.ringius.pureMaps.command

/usr/share/dbus-1/[...].service
[D-BUS Service]
Name=io.github.ringius.pureMaps
Exec=/usr/bin/sailfish-qml harbour-pure-maps

**Comment by xXSparkeyy** [comment]
The above would eliminate the need for an exe script (if you mean exe script as in opening the app if not already and stuff)

**Comment by rinigus** [comment]
Interesting, that would sidestep checking dbus and other issues probably. Do you happen to know a similar setup for regular Linux? I presume its without X-Maemo-Service? :)

**Comment by xXSparkeyy** [comment]
Yes there is [D-Bus Activation](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html). Is there a qml dbus binding like nemo's DBusAdaptor for the other platforms?

**Comment by rinigus** [comment]
Yes, its ported to Linux and maybe even available in debian (not 100% sure). Will look into this activation, although it maybe problematic if used with flatpak.

**Comment by rinigus** [comment]
Corrected: there is a way to use it in flatpak as well.

**Comment by rinigus** [comment]
We are almost there. DBus activation is impossible due to https://bugs.merproject.org/show_bug.cgi?id=2029 , for now I used bash script that is essentially having similar functionality. 

The only unfinished part is association of `geo:` URI with Pure Maps. On flatpak, it works perfectly by just specifying MimeType in desktop file. Looks like its insufficient in SFOS, as this association is not propagated from https://github.com/rinigus/pure-maps/blob/master/data/harbour-pure-maps.desktop further. Any ideas?

**Comment by xXSparkeyy** [comment]
I think the most elegant solution would be to implement the D-Bus Activation Interface for the other platforms and keep the current for sfos. Since other platforms should ignore the x-maemo dbus lines and SFOS the DBus activation line, a universal .desktop file (In addition to the visible one) could be kept. For the association of the `geo:` uri, the desktop file should just contains the `x-maemo-urischeme\geo` (on my outdated SFOS version) and `x-schemehandler/geo` (on newer versions and probably other platforms), additionaly `~/.local/share/applications/mimeapps.list` could be edited to set pure-maps as preferred application, which should be possible in an upcoming version of mimer.
Alternatively you could just add a desktop file containing `Exec=dbus-send [...]`, since the Exec line of the .service file will be executed, if the interface wasn't avaiable. This should work on all platforms that use d-bus.

**Comment by rinigus** [comment]
D-Bus Activation Interface is impossible (or requires moving DBus to python or somewhere else) until Nemo DBus QML plugin issue is resolved. That's for normal Linux, not sure whether SFOS uses something else for dbus activation. 

Line 
```
MimeType=x-scheme-handler/geo
```
is in desktop file already. When using Flatpak, all seems to work fine. In SFOS, after manually adding a line with `x-scheme-handler/geo`, xdg-open starts Pure Maps or communicates with it, as expected. However, no communication from browser.

I am closing this issue for now - cmd line option and communication via dbus is implemented. If mimer will add geo: support, we'll be all set, I think.

**Comment by rinigus** [comment]
PS: feel free to comment on closed issue as well :)

**Comment by xXSparkeyy** [comment]
Hi, just found out you can indeed connect to signals with uppercase names by appending 'rc'
https://git.merproject.org/mer-core/nemo-qml-plugin-dbus/blob/master/src/plugin/declarativedbusadaptor.cpp#L390

**Comment by hsjpekka** [comment]
Hi, I tried _harbour-pure-maps kaivokatu_ in terminal to search for _kaivokatu_. It did not work, unless puremaps was already running. If puremaps was running, it opened the search page with some results.
I'm using 2.6.0-1.15.1.jolla & sfos 3.4.

Below is the output of two consecutive _harbour-puremaps kaivokatu_'s. Perhaps the problem is described on line
`[W] unknown:92 - file:///usr/lib/qt5/qml/Sailfish/Silica/PageStack.js:92: Error: Cannot push while operation is in progress: push
` Is it trying to open the search page too early?
`Quitting` is the result of me closing the app.

>Script started on 2021-05-30 11:45:41+03:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="56" LINES="66"]
[nemo@Xperia10-DualSIM ~]$ harbour-pure-maps kaivokatu&
[1] 19249
[nemo@Xperia10-DualSIM ~]$ Current locale: fi_FI
Loaded translation
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Got library name:  "/usr/lib/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
[D] onCompleted:433 - Warning: specifying an object instance for initialPage is sub-optimal - prefer to use a Component
[D] unknown:0 - Geoclue client path: "/org/freedesktop/Geoclue/Master/client14"
Started DBus service at io.github.rinigus.PureMaps
[D] unknown:0 - Cannot convert: QVariant(void*, 0x0)
GET https://photon.komoot.io/api/?q=kaivokatu&limit=10&lang=en&lon=22.760&lat=61.234
Establishing connection to photon.komoot.io
[W] unknown:92 - file:///usr/lib/qt5/qml/Sailfish/Silica/PageStack.js:92: Error: Cannot push while operation is in progress: push
[W] unknown:0 - [ INFO ]  "{unknown}[General]: GPU Identifier: Adreno (TM) 508"
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
harbour-pure-maps kaivokatu&
[2] 19387
[nemo@Xperia10-DualSIM ~]$ Current locale: fi_FI
Loaded translation
[D] unknown:0 - Cannot convert: QVariant(void*, 0x0)
Command line arguments forwarded to running instance. Closing
[W] unknown:518 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/PulleyMenuBase.qml:518:29: Unable to assign [undefined] to float
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
[W] unknown:0 - QObject::startTimer: Timers cannot have negative intervals
Quitting
Calling http.pool.terminate
Closing connection https:photon.komoot.io:3860345544
Connecttion https:photon.komoot.io:3860345544 closed
Calling poor.conf.write
Calling self.history.write
Closing voice engines
All quit methods called
exit
exit
>
>Script done on 2021-05-30 11:47:15+03:00 [COMMAND_EXIT_CODE="0"]

**Comment by hsjpekka** [comment]
And, what kind of URI is supported - or is readme.md back in future? I tried _harbour-pure-maps map://?q=kaivokatu_ which resulted in something like
`https://photon.komoot.io/api/?q=map%3A%2F%2F...kaivokatu&limit=10&lang=en&lon=22.760&lat=61.234`. So it considered `map://?q=kaivokatu` as the address to search for.
Btw. I'm trying to use patch _Show calendar event location_, which requires URI support at the moment.

**Comment by rinigus** [comment]
Looks like it is a bug that got introduced at some point.

`harbour-pure-maps kaivokatu` should search for it using geocoder, no `map://` prefix is needed. See https://github.com/rinigus/pure-maps#command-line-options

I will look into it. As for timing, not sure when - may take 1-2 weeks, unfortunately.

**Comment by hsjpekka** [comment]
How about adding something like

> 	  QString addressTag = "address=";
>	  if (!isGeo && location.contains(addressTag, Qt::CaseInsensitive))
>	    {
>		  int i = location.indexOf(addressTag) + addressTag.length();
>		  int j = location.indexOf("&", i);
>		  isGeo = true;
>		  Commander::instance()->search(location.mid(i,j));
>		}

in CmdLineParser::process(). That way URI, Qt.openUrlExternally() and xdg-schemehandlers could be used to start the app and set the address.

**Comment by rinigus** [comment]
Yes, will have to take a look. Will pick this up a bit later, hopefully next week.

**Comment by rinigus** [comment]
It should work now as expected according to the API: 
- geo: uri opens location and tries to identify it with the reverse geocoding
- just string enters it to search

Closing. Reopen if it is not working as it should in the next release
